### Footstep parameterization for a large humanoid, similar to ASIMO or HRP-2 #

### footstep settings #########################################################
# Footstep displacement vectors (in meter / rad)
# WARNING: data type has to be float/double, integers will cause an exception
footsteps:
# x:     [0.00, 0.30, 0.40, -0.2, 0.35, 0.30, 0.40, -0.20, -0.20, -0.30, 0.40, 0.35, 0.3,  0.25]
# y:     [0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,   0.2,   0.2,   0.2,  0.2,  0.2,  0.2,  0.2]
# theta: [0.00, 0.00, 0.00, 0.70, 0.30,-0.40, 0.00,  0.30,  0.00,  0.00, 0.00, 0.00, 0.00,-0.25]

#  x: [0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.20, 0.30, 0.30, 0.30, 0.30, 0.30, 0.30, 0.40, 0.40, 0.40, 0.40, 0.50, 0.50, -0.10, -0.10, -0.10, -0.20, -0.20]
#  y: [0.25, 0.25, 0.25, 0.25, 0.30, 0.30, 0.30, 0.30, 0.25, 0.25 ,0.25, 0.30, 0.30 ,0.30, 0.25, 0.25 ,0.25, 0.30, 0.25, 0.30,  0.25,  0.25,  0.25,  0.25,  0.20]
#  theta: [0.00, 0.10, 0.20, 0.40, 0.00, 0.10, 0.20, 0.40, 0.00, 0.10, 0.20, 0.00, 0.10, 0.20, 0.00, 0.10, 0.00, 0.10, 0.00, 0.00, 0.00, 0.20,  0.40, 0.00, 0.10]

 x:     [-0.3,-0.3,-0.3,-0.3,-0.3,-0.3,-0.3,-0.3,-0.3,-0.3,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.2,-0.1,-0.1,-0.1,-0.1,-0.1,-0.1,-0.1,-0.1,-0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.3,0.3,0.3,0.3,0.3,0.3,0.4,0.4,0.4,0.4,0.5,0.5]
 y:     [0.25,0.25,0.3,0.3,0.25,0.25,0.25,0.3,0.3,0.3,0.25,0.25,0.25,0.3,0.3,0.3,0.25,0.25,0.25,0.25,0.3,0.3,0.3,0.3,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.3,0.4,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.3,0.3,0.3,0.3,0.25,0.25,0.25,0.3,0.3,0.3,0.25,0.25,0.25,0.3,0.25,0.3]
 theta: [-0.1,-0.2,-0.1,-0.2,0.0,0.1,0.2,0.0,0.1,0.2,-0.1,-0.2,-0.4,-0.1,-0.2,-0.4,0.0,0.1,0.2,0.4,0.0,0.1,0.2,0.4,0.0,-0.1,-0.2,-0.3,-0.4,0.1,0.2,0.3,0.4,0.0,0.2,0.4,0.6,0.7,0.0,0.0,0.1,0.2,0.3,0.4,0.0,0.1,0.2,0.4,0.0,0.1,0.2,0.4,0.0,0.1,0.2,0.0,0.1,0.2,0.0,0.1,0.0,0.1,0.0,0.0]








### foot settings #############################################################
foot:
  size: {x: 0.27, y: 0.18, z: 0.015}
  separation: 0.25
  origin_shift: {x: 0.02, y: 0.0}
  max:
    step: {x: 0.50, y: 0.30, theta: 0.7}
    inverse:
      step: {x: -0.30, y: 0.25, theta: -0.3}


### step range ################################################################

# more accurate than the bounding box defined by the max/max inverse step
step_range:
 x: [0.4, 0.4,-0.30,-0.30]
 y: [0.2, 0.2, 0.2, 0.2]
