# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftElbowPitch:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
  leftForearmYaw:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  leftShoulderPitch:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
  leftShoulderRoll:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
  leftShoulderYaw:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
  leftWristPitch:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  leftWristRoll:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  rightElbowPitch:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
  rightForearmYaw:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  rightShoulderPitch:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
  rightShoulderRoll:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
  rightShoulderYaw:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
  rightWristPitch:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  rightWristRoll:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  torsoPitch:
    has_velocity_limits: true
    max_velocity: 9
    has_acceleration_limits: false
    max_acceleration: 0
  torsoRoll:
    has_velocity_limits: true
    max_velocity: 9
    has_acceleration_limits: false
    max_acceleration: 0
  torsoYaw:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0