# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftElbowPitch:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.164
    max_position: 0.11
  leftForearmYaw:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.009 
    max_position: 3.13
  leftShoulderPitch:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.84
    max_position: 1.99
  leftShoulderRoll:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -1.509 
    max_position: 1.256
  leftShoulderYaw:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -3.09
    max_position: 2.17
  leftWristPitch:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -0.35 
    max_position: 0.48
  leftWristRoll:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -0.61 
    max_position: 0.615
  rightElbowPitch:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -0.11  
    max_position: 2.164
  rightForearmYaw:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position:-2.009 
    max_position: 3.13
  rightShoulderPitch:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -2.84
    max_position: 1.99
  rightShoulderRoll:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -1.256 
    max_position: 1.509
  rightShoulderYaw:
    has_velocity_limits: true
    max_velocity: 11.5
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -3.09 
    max_position: 2.17
  rightWristPitch:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0 
    min_position:-0.47 
    max_position: 0.35
  rightWristRoll:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    min_position: -0.615  
    max_position: 0.61
  torsoPitch:
    has_velocity_limits: true
    max_velocity: 9
    has_acceleration_limits: false
    max_acceleration: 0
  torsoRoll:
    has_velocity_limits: true
    max_velocity: 9
    has_acceleration_limits: false
    max_acceleration: 0
  torsoYaw:
    has_velocity_limits: true
    max_velocity: 5.89
    has_acceleration_limits: false
    max_acceleration: 0
